# -*- coding: utf-8 -*-
"""Hand on lab analyzing historical stock / revenue data and building a dashboard .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIw3SBc7AVhsHZGrozha-2JAHKzWsEEz
"""

import pandas as pd
import yfinance as yf

print("Everything is working!")

import yfinance as yf

tesla = yf.Ticker("TSLA")

tesla_data = tesla.history(period="max")

tesla_data.reset_index(inplace=True)

tesla_data.head()

import pandas as pd
import requests
from bs4 import BeautifulSoup

url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"

html_data = requests.get(url).text

soup = BeautifulSoup(html_data, "html.parser")

tesla_revenue = pd.DataFrame(columns=["Date","Revenue"])

for row in soup.find_all("tbody")[0].find_all("tr"):
    col = row.find_all("td")

    if len(col) != 0:
        date = col[0].text
        revenue = col[1].text

        tesla_revenue = pd.concat(
            [tesla_revenue,
             pd.DataFrame({"Date":[date],
                           "Revenue":[revenue]})],
            ignore_index=True
        )

tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace(",","")
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace("$","",regex=False)

tesla_revenue.tail()

gme = yf.Ticker("GME")

gme_data = gme.history(period="max")

gme_data.reset_index(inplace=True)

gme_data.head()

url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/gamestop_revenue.htm"

html_data = requests.get(url).text

soup = BeautifulSoup(html_data, "html.parser")

gme_revenue = pd.DataFrame(columns=["Date","Revenue"])

for row in soup.find_all("tbody")[0].find_all("tr"):
    col = row.find_all("td")

    if len(col) != 0:
        date = col[0].text
        revenue = col[1].text

        gme_revenue = pd.concat(
            [gme_revenue,
             pd.DataFrame({"Date":[date],
                           "Revenue":[revenue]})],
            ignore_index=True
        )

gme_revenue["Revenue"] = gme_revenue["Revenue"].str.replace(",","")
gme_revenue["Revenue"] = gme_revenue["Revenue"].str.replace("$","",regex=False)

gme_revenue.tail()

import pandas as pd

gme_revenue = pd.DataFrame({
    "Date": ["2020", "2019", "2018", "2017", "2016"],
    "Revenue": [6466, 8285, 8547, 7965, 9364]
})

gme_revenue

import plotly.graph_objects as go
from plotly.subplots import make_subplots

def make_graph(stock_data, revenue_data, stock):

    fig = make_subplots(
        rows=2,
        cols=1,
        subplot_titles=("Stock Price", "Revenue")
    )

    fig.add_trace(
        go.Scatter(
            x=stock_data['Date'],
            y=stock_data['Close'],
            name="Stock Price"
        ),
        row=1,
        col=1
    )

    fig.add_trace(
        go.Scatter(
            x=revenue_data['Date'],
            y=revenue_data['Revenue'],
            name="Revenue"
        ),
        row=2,
        col=1
    )

    fig.update_layout(
        title=stock,
        height=800
    )

    fig.show()

make_graph(tesla_data, tesla_revenue, "Tesla")

make_graph(gme_data, gme_revenue, "GameStop")

